### ISSUE TITLE
Refactor location of `.hbs` files in repo

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-bunsen#161]
It's not the best practice to have our template files in `app/`, so let's move them to a more appropriate place in `addon/`

**Comment by rox163** [comment]
Yes please. With this move to `addon/templates`, bunsen templates are properly visible inside an engine and render correctly.

**Comment by sglanzer** [comment]
@rox163 did you do this locally?  Want to PR a fix?

**Comment by rox163** [comment]
I did but Matt already has these changes made in his set of changes coming in for 7.0.0 soon. I also have a bunch of other stuff for the engine but dont want to PR yet that we should quickly chat about :)
