### ISSUE TITLE
When an array has defaults, the first item added doesn't get the joke

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-bunsen#174]
As pointed out by `mstaffor` in Slack:

> quick question. for the example of the Model `Array with Defaults`, is there a reason that the first superhero added does not get supplied with the defaults, but the additional ones do ?

![pasted_image_at_2016_08_31_09_22](https://cloud.githubusercontent.com/assets/411788/18123913/3f8b6fa0-6f2d-11e6-87fc-b3481fe04ebd.png)

That is certainly a bug.

**Comment by sandersky** [comment]
I have a solution for this between my `bunsen-core` and `ember-frost-bunsen` forks. I just need to add a bunch of tests to `bunsen-core` around the reducer since it is severely lacking tests, then I'll get PR's out to fix the issue.
