### ISSUE TITLE
Facets: dropdown select doesn't clear when use more than once

### ISSUE THREAD

**Issue by sglanzer** [ciena-frost/ember-frost-bunsen#372]
Moving this from the object browser repo since the facets are handled by sub-components (bunsen in this case) - may no longer be an issue.

@pbosse:
To reproduce simply use the dropdown to select a filter.
Click the clear.
The value is cleared
Use the dropdown again and select a filter
Click the clear
The value is not cleared.

Note that the proper event is fired, so that if you une the onFilter, you do receive the event

**Comment by sandersky** [comment]
Can't reproduce with the latest bunsen and object browser.
