### ISSUE TITLE
Programmatically validate form?

### ISSUE THREAD

**Issue by lumenlunae** [ciena-frost/ember-frost-bunsen#374]
I have a situation where I have a boolean property (so, a checkbox) that is required. If the user does nothing but press a submit button right away, that property is null and no change or validation has been performed. 

I'd like to be able to trigger validation after pressing the submit button to make sure the form has all required fields input, if possible. 

If there's a way to do this already, sorry for the trouble. I really appreciate the library! :)

**Comment by sandersky** [comment]
You simply need to set `showAllErrors=true` on your `frost-bunsen-form` or `frost-bunsen` instance once the submit button has been pressed. This tells bunsen to go ahead and flag all errors regardless of whether or not the user has focused on individual inputs yet.
