### ISSUE TITLE
Refactor to remove usage of ember-simple-uuid dependency

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-bunsen#489]
Have not looked at the code in this repo specifically but in other repos have been able to use `guidFor` off of `Ember` and replace `uuid()` with `guidFor({})`.

**Comment by notmessenger** [comment]
Will be evaluated in #491

**Comment by juwara0** [comment]
This was evaluated in https://github.com/ciena-frost/ember-frost-bunsen/issues/489 and it was found that `ember-simple-uuid` and it's dependent package `node-uuid` were not being used to set a `uuid` in this add-on. In PR https://github.com/ciena-frost/ember-frost-bunsen/pull/505 both `ember-simple-uuid` and it's dependent package `node-uuid` were removed.
