### ISSUE TITLE
User is able to copy a string value in field of type number

### ISSUE THREAD

**Issue by goforsatish** [ciena-frost/ember-frost-bunsen#528]
Are you opening a **BUG REPORT** or a **FEATURE REQUEST / CODE CHANGE**?

There is a section for each below.  Please complete the appropriate section and remove the other one.

We realize there is a lot of data requested here. We ask only that you do your best to provide as much information as possible so we can better help you.
![screen shot 2018-05-28 at 10 36 49 am](https://user-images.githubusercontent.com/33549703/40598059-1bb4f558-6263-11e8-898b-19c097129f3f.png)

# BUG REPORT

* [x] I have ensured that the issue isn't already reported
* [x] I have confirmed that the issue is reproducible with the latest released version
* [x] I have deleted the **FEATURE REQUEST / CODE CHANGE** section

## Summary
* Provide a general summary of the issue in the title above
User is able to copy a string value in field of type number. For instance, user is able to enter value like 0..255 in a field of type number. User should not able able to enter any invalid type value in number field. 
## Expected Behavior
* What should happen?
Once user copy any value like 0..255 i.e not of prescribed format then it should be discarded .

## Actual Behavior
User is able to copy a string value in field of type number. For instance, user is able to enter value like 0..255 in a field of type number. User should not able able to enter any invalid type value in number.

## Possible Solution
* Not obligatory, but suggest a fix/reason for the bug
Once user copy any value like 0..255 i.e not of prescribed format then it should be discarded .

## Steps to Reproduce
Input a value like 0..255 using copy paste command in field of type number. This invalid format value is displayed in the field, however it's not considered as a field input. 

---

* [ ] Include the contents of your _package.json_ file
* [ ] Steps to reproduce:
  1.
  2.
  3.
  4.
  ...

## Context
* How has this issue affected you? What are you trying to accomplish?
* Providing context helps us come up with a solution that is most useful in the real world.

## Environment

(answer all that are applicable)

* [ ] I am using the latest released version (can check with `npm ls <package-name>`)
* I am using these browsers:
  * [ ] Latest Chrome
  * [ ] Latest Firefox
* [ ] My version of `Node` is:
* [ ] My version of `npm` is:
* [ ] My OS is:
* [ ] Include the contents of your _package.json_ file

**Comment by sophypal** [comment]
Bunsen is leveraging the `input` of type `number` which doesn't prevent alphanumeric input in all browsers. It's the browser's responsibility to allow/disallow valid characters. Doing so in Bunsen is problematic for a lot of reasons. For example, if you use typed `.` to begin a decimal, using a `parseInt` implementation would yield `NaN` even though it's a valid character. The implementation would have to be smarter about the context and putting that much client side validation in Bunsen is complex is better left as a validation error instead of a character filter.
