### ISSUE TITLE
consider removing 'bunsen' from consumable component names

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-bunsen#8]
The consumer should be able to use 'frost-form' instead of 'frost-bunsen-form' for example.

**Comment by job13er** [comment]
As long as `bunsen` is in the repo/project name, I think it makes sense to have `bunsen` in the component name as well.

**Comment by rox163** [comment]
Maybe when this repo is split out into two or more components, [as I think was originally planned], then we can look at naming.

**Comment by sglanzer** [comment]
My only goal with the naming of this project/component is making sure that people know what `bunsen` means - really we're talking about `data-driven` right?

**Comment by job13er** [comment]
Yes, which is why I had suggested we rename it when moving to open source, but, if I recall correctly, you said it works fine.

**Comment by sglanzer** [comment]
I'm comfortable with keeping the naming, we'll just stamp `data-driven` all over the docs.  Bunsen will also be in the background for most things, the exception being forms (as it's currently written).  When we look at making the projects more modular we may want to consider `ember-frost-form` with bunsen as the driver - kind of pitching here because I don't see a benefit in causing a ruckus about this right now.

**Comment by job13er** [comment]
Sounds good

**Comment by sandersky** [comment]
@sglanzer can I close this issue?

**Comment by sglanzer** [comment]
@sandersky You can, but we should do some work to up the exposure of this project.  As mentioned previously it's not categorized with forms in ember-observer and while it is highly rated I don't think it has been widely discovered yet.

Maybe we can raise some issues to:

1.  Add some more relevant keywords
2.  Fix the categorization on ember-observer
3.  Write a blog post to demonstrate the intent and usefulness of the project

Thoughts?

**Comment by sandersky** [comment]
I agree, which brings me to one of my annual goals: to create a Ciena UX developer blog.

**Comment by job13er** [comment]
Also, let's clean up documentation before shining a light on it. It is an awesome library, but its documentation is far less awesome.

**Comment by sandersky** [comment]
@job13er I couldn't agree more. I've made a couple attempts to improve it but there is just so much to document.

**Comment by sglanzer** [comment]
@EWhite613 has the blog setup, we just need to start writing content - he can provide details on how to write posts
