### ISSUE TITLE
For consistency across Frost, use dasherized event names in templates

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-bunsen#9]
for example, `on-change` instead of `onChange`

**Comment by sandersky** [comment]
When this is addressed I'd recommend making it support both `onChange` and `on-change` so we don't have to apply a major version bump as this would be a breaking change. Then later when we need a major version bump for something else we could think about remove the camel case version `onChange`.

**Comment by sglanzer** [comment]
Completely agree with @sandersky - keep the prior as a deprecated format

**Comment by psbanka** [comment]
Closed by jira-gh-sync

**Comment by psbanka** [comment]
Closed by jira-gh-sync

**Comment by psbanka** [comment]
Closed by jira-gh-sync
