### ISSUE TITLE
frost-bunsen does not work with IE11

### ISSUE THREAD

**Issue by vesper2000** [ciena-frost/ember-frost-bunsen#92]

**Comment by sandersky** [comment]
Update demo app to use babel's polyfill which got past the previous error in IE 11 but now it dies around Mirage:

<img width="1035" alt="screen shot 2016-10-20 at 1 19 46 pm" src="https://cloud.githubusercontent.com/assets/422902/19576463/f371b120-96c7-11e6-8a8e-c397dbc30ac2.png">

**Comment by sandersky** [comment]
Fixed
